### PR TITLE
Implement HTTPS Support with SSL/TLS and HTTP to HTTPS Redirection

### PR DESCRIPTION
**Pull request by Guhapriya01**
This pull request implements HTTPS and SSL/TLS support for the Java HTTP server and introduces HTTP to HTTPS redirection.

### Changes Made:
- **SSL/TLS Support:**
  - Generated a self-signed SSL certificate using `keytool` for development and testing.
  - Integrated the SSL certificate using JSSE to enable HTTPS.
  - Configured the server to load the generated keystore and use the SSL certificate for encrypted communication on port `8043`.

- **HTTP to HTTPS Redirection:**
  - Implemented logic to listen for HTTP requests on port `8080`.
  - Redirected HTTP requests to the corresponding HTTPS URL with a `301 status code`.

### Output:
To verify the implementation, you can test the following commands:

1. **HTTP to HTTPS Redirection:**
   ```bash
   curl -i http://localhost:8080
   ```
   **Response:**
   ```
   HTTP/1.1 301 Moved Permanently
   Location: https://172.25.224.1:8043/
   Connection: close
   ```

2. **Accessing the HTTPS Server:**
   ```bash
   curl -ik https://localhost:8043
   ```
   **Response:**
   ```
   HTTP/1.1 200 OK
   Content-Length: 109

   <html><head><title>Simple Java HTTPS Server</title></head><body>This page was served using Java</body></html>
   ```

### Steps to Create a Self-Signed Certificate:
1. **Open Command Prompt** and navigate to the directory where you want to create your keystore.
2. **Generate the Self-Signed Certificate:**
   Use the following command to create a keystore and generate a self-signed SSL certificate:
   ```bash
   keytool -genkeypair -alias myserver -keyalg RSA -keysize 2048 -keystore keystore.jks -validity 365
   ```
   - You will be prompted to enter information for the certificate. Fill in the required details such as your name, organization, and location.
3. **Enter a Password** for the keystore when prompted. Remember this password as it will be used in the server configuration.
4. **The `keystore.jks` file** will be created in the current directory. This file contains the self-signed certificate.

In the `ssl-config.json` file, replace the keystore path with the path where you created the file, and use the same password for both the keystore and key password.

Related issues : #7

Please review the changes and let me know if any modifications are needed!

### CODE REVIEW

**Review by ajaynegi45 — CHANGES_REQUESTED** [review]
Hi @Guhapriya01,

Thank you for your prompt work on this issue. I appreciate your dedication to the project.

I have reviewed your work, and I need some changes.

- resolve these conflicts.
 ```
This branch has conflicts that must be resolved
 to resolve conflicts before continuing.
Conflicting files
src/main/java/com/httpserver/HttpServerApplication.java
src/main/java/com/httpserver/config/Configuration.java
src/main/java/com/httpserver/config/ConfigurationManager.java
src/main/java/com/httpserver/core/HttpConnectionWorkerThread.java
src/main/java/com/httpserver/core/ServerListenerThread.java
```

 Once again, thank you for your contribution! ❤️

**Comment by Guhapriya01** [comment]
Thank you so much @ajaynegi45  for reviewing my work and for your kind words! 

I will resolve the conflicts and make the necessary changes to ensure everything works smoothly. I'll get back to you as soon as it's done.

**Comment by ajaynegi45** [comment]
> Thank you so much @ajaynegi45 for reviewing my work and for your kind words!
> 
> I will resolve the conflicts and make the necessary changes to ensure everything works smoothly. I'll get back to you as soon as it's done.

Just fetch update from the upstream main branch

**Comment by Guhapriya01** [comment]
Hi @ajaynegi45, 

I’ve committed the changes and resolved the conflicts. Let me know if you need anything else!

**Review by ajaynegi45 — APPROVED** [review]
Hi @Guhapriya01,

Thank you for your prompt work on this issue. I appreciate your dedication to the project.

I have reviewed your work, and I'm pleased to inform you that I have merged your pull request. Your changes looks fantastic, and it aligns perfectly with the project's design and usability goals. Great job!

If you have any more contributions or if there's anything else you'd like to work on in the future, please don't hesitate to let us know. Your efforts are valuable to the project's success.

Once again, thank you for your contribution! ❤️

**Comment by Guhapriya01** [comment]
Thank you @ajaynegi45! 😊 I'm glad the changes worked well. Looking forward to contributing more!

**Pull request merged**
